services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      ALLOWED_ROOT: /app/shared
    volumes:
      - ./sample-files:/app/shared

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
